version: '3'

services:
  php_cargo:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/cargo:cached
    networks:
      - cargo-network
networks:
  cargo-network:
    driver: bridge

